Add homepage, todo page with Google sign in auth and API endpoints for todo
PratibhaShrivastav/SPS-Team-Project pull request #9
Opened 2020-08-13 14:41 UTC by PratibhaShrivastav

2020-08-20 11:06 UTC, yashjaing requested changes

2020-08-20 11:06 UTC, yashjaing commented on src/main/java/com/google/sps/data/ResponseStatus.java
> +    private final String status_message;
camel case for java

2020-08-20 11:06 UTC, yashjaing commented on src/main/java/com/google/sps/servlets/MarkTodoServlet.java
> +    private static final String TIMESTAMP_PROPERTY = "timestamp";
same

2020-08-20 11:06 UTC, yashjaing commented on src/main/java/com/google/sps/servlets/MarkTodoServlet.java
> +        long entityID = Integer.parseInt(request.getParameter("EntityID"));
you already have the keys as string constants. use them

2020-08-20 11:06 UTC, yashjaing commented on src/main/java/com/google/sps/servlets/ReviewServlet.java
> +    private static final String TIMESTAMP_PROPERTY = "timestamp";
looks like the same constants everywhere...can you please create a common/Constants.java and use that everywhere?

2020-08-20 11:06 UTC, yashjaing commented on src/main/java/com/google/sps/servlets/TodoListServlet.java
> +        List<BaseEntity> todo_list = new ArrayList<>();
case :(

2020-08-20 11:06 UTC, yashjaing commented on src/main/java/com/google/sps/servlets/UnmarkTodoServlet.java
> +        ResponseStatus responseStatus = ResponseStatus.builder().status_code(HttpServletResponse.SC_OK).status_message("OK").build();
message is not required

2020-08-20 11:06 UTC, yashjaing commented on src/main/webapp/assets/javascript/app.js
> +        codeHTML += '<div class="rating">Rating: ' + voteAverage + '/10</div><br>';
can this be a single string.. I am afraid so many concats will bring in in-efficiency

2020-08-23 05:29 UTC, anishajain22 commented on src/main/webapp/assets/javascript/app.js
> +        codeHTML += '<div class="rating">Rating: ' + voteAverage + '/10</div><br>';
Noted. Modified.

2020-09-05 11:05 UTC, merged